### ISSUE TITLE
About Running the Single Coil

### ISSUE THREAD

**Issue by GeraldGore** [pputzky/irim_fastMRI#3]
Hello,

I have been always facing run_model.py: error: the following arguments are required: --data-path, --out-dir in this line.

python -m scripts.run_model --challenge singlecoil --batch-size 8 \ --data-path $test --checkpoint $chkpt/best_model.pt \ --out-dir $output --data-split test_v2 --mask-kspace

test = '/content/drive/My Drive/knee_singlecoil_test_v2/singlecoil_test_v2/'
output='/content/drive/I-RIM_Denemeler/Output/'
chkpt='/content/drive/My Drive/I-RIM/pretrained.z03/'

What is the problem? Could you give me some information about this error?

Thanks,

**Comment by wdika** [comment]
Hi @GeraldGore, according to [training_utils/data_loaders.py](https://github.com/pputzky/irim_fastMRI/blob/ef0d8c534bdcf7aaa69de9087ee6072223cc3d80/training_utils/data_loaders.py#L67) the root path is set as 
`args.data_path / f'{args.challenge}_{args.data_split}'`. 

So, the `--data-path` should be `/content/drive/My Drive/knee_singlecoil_test_v2/`.
