### ISSUE TITLE
mask while testing

### ISSUE THREAD

**Issue by hellopipu** [pputzky/irim_fastMRI#7]
Hi,

Thanks for sharing your code here.

I have a question about the mask usage while testing.  If I understand your code correctly, while testing, the input img is cropped to 320, but the mask is still original kspace shape, so there should be error for this `x = mask * x` in `mse_gradient` function. Did I miss something  ?

**Comment by pputzky** [comment]
Hi,

Thanks for your interest in the code. The reconstructions are run on the sub-sampled K-space for the full image. Image sizes vary across volumes. After reconstruction, the central portion of the 320x320 image patch is cropped and used for evaluation (this is in accordance with the fastMRI paper). I'll close this issue. I hope you'll find this code useful.
